version: '3.7'

services:
  nginx:
    image: nginx
    network_mode: host
    container_name: fullstacked-nginx
    volumes:
      - ./:/apps
      - ./root.conf:/etc/nginx/nginx.conf
    restart: always
