version: '3.7'

services:
  nginx:
    image: nginx
    network_mode: host
    container_name: fullstacked-nginx
    volumes:
      - ./:/apps
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
    restart: always
